"""empty message

Revision ID: 660b69a74bc5
Revises: c288f4b381f9
Create Date: 2022-07-24 18:54:20.930332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660b69a74bc5'
down_revision = 'c288f4b381f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('planetsid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planetsid'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_planet')
    # ### end Alembic commands ###
