"""empty message

Revision ID: c4a1e4abfa21
Revises: 29557846e5f2
Create Date: 2022-07-22 01:13:23.156612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4a1e4abfa21'
down_revision = '29557846e5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('gravity', sa.String(length=60), nullable=False))
    op.add_column('planets', sa.Column('terrain', sa.Integer(), nullable=False))
    op.drop_column('planets', 'weight')
    op.drop_column('planets', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('location', mysql.VARCHAR(length=60), nullable=False))
    op.add_column('planets', sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('planets', 'terrain')
    op.drop_column('planets', 'gravity')
    # ### end Alembic commands ###
