"""empty message

Revision ID: f722c379de27
Revises: 4490695e71b9
Create Date: 2022-07-23 00:12:01.191291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f722c379de27'
down_revision = '4490695e71b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('terrain', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'terrain')
    # ### end Alembic commands ###
